---
name: "Test"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build all
      run: |-
        ./pleasew build -p -v=2 //...

    - name: Print please-buildkit logs
      if: always()
      run: |-
        set -x
        cat plz-out/log/please-buildkit-buildkitd.log
        cat plz-out/log/please-buildkit-worker.log

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test all
      run: |-
        ./pleasew test -p -v=2 //...
